# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.5"

  config.ssh.username = "root"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = "true"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "router" do |config|
    config.vm.hostname = "router"

    config.vm.network "private_network", ip: "10.0.0.10"
  end

end
